#!/bin/bash

source ./config.cfg

readonly vendor_dir="vendor"
readonly version="1.0.0"

print_help() {
	cat <<-EOF
	Smash $version By Nat Zimmermann
	EOF
}

print_version() {
	echo "$version"
}

# Replace non-alphanumeric characters with dashes
# Replace uppercase characters with their lowercase counterparts
sluggify() {
	echo "${@:1}" | tr -c '[:alnum:]\n' '-' | tr '[:upper:]' '[:lower:]'
}

new_post() {
	mkdir -p "$post_dir"

	local readonly title="${@:1}"
	local readonly file_name="$post_dir/$(date +%Y-%m-%d)-$(sluggify $title).md"

	# If file already exists, append a number to the end until valid
	local i=1
	while [ -f "$file_name" ]; do
		file_name="$post_dir/$(date +%Y-%m-%d)-$(sluggify $title)-$i.md"
		i=$((i + 1))
	done

	touch "$file_name"

	echo "$file_name created!"
}

build() {
	if [ ! -f "$vendor_dir/markdown.sh" ]; then
		echo "Dependencies not installed, please run ./smash install"
		return 1
	fi

	mkdir -p "$public_dir"

	local readonly posts="$post_dir/*"
	local readonly layout=$(cat "$layout_dir/default.html")

	for post in $posts; do
		echo ${layout//@content/$(sh "$vendor_dir/markdown.sh" "$post")} > "$public_dir/index.html"
	done
}

install() {
	echo "Creating directories"
	local readonly directories_to_create=(
		$post_dir
		$public_dir
		$layout_dir
	)

	for directory in "${directories_to_create[@]}"; do
		if [ ! -d "$directory" ]; then
			mkdir -p "$directory"
		fi
	done

	echo "Installing dependencies"
	if [ ! -f "$vendor_dir/markdown.sh" ]; then
		curl -o "$vendor_dir/markdown.sh" "https://raw.githubusercontent.com/chadbraunduin/markdown.bash/master/markdown.sh"
	fi
	echo "Installed!"
}

case "$1" in
	install)
		install
		;;
	build)
		build
		;;
	new)
		new_post "${@:2}"
		;;
	version)
		print_version
		;;
	*)
		print_help
		;;
esac
